import { initialLot, Lot } from "../lot/lot.interface";

export interface Product {
    readonly id: string,
    sku: string,
    gtin: string,
    ncm: string,
    cest: string,
    cfop: string,
    category: string,
    brand: string,
    model: string,
    minimumStock: number,
    maximumStock: number,
    reservedStock: number,
    availableStock: number,
    bulk: number,
    grossWeightMeasurement: number,
    netWeightMeasurement: number,
    grossWeight: number,
    netWeight: number,
    url: string,
    lot: Lot,
}

export const initialProduct: Product = {
    id: '',
    sku: '',
    gtin: '',
    ncm: '',
    cest: '',
    cfop: '',
    category: '',
    brand: '',
    model: '',
    minimumStock: 0,
    maximumStock: 0,
    reservedStock: 0,
    availableStock: 0,
    bulk: 0,
    grossWeightMeasurement: 0,
    netWeightMeasurement: 0,
    grossWeight: 0,
    netWeight: 0,
    url: '',
    lot: initialLot,
}