export const vector: string[][] = [
    ["user", "people-circle", "first"],
    ["leafletMap", "calendar3", "second"],
    // ["list", "calendar3", "second"],
    // ["google", "toggles2", "third"],
    ["location", "table", "fourth"],
    // ["food_category", "table", "fourth"],
    // ["military", "chat-quote-fill", "fifth"],
    // ["composite_unit", "collection", "sixth"],
    // ["weather", "table", "sixth"],
    // ["weatherOffShore", "home", "sixth"],
    // ["weatherOnShore", "speedometer2", "sixth"],
    // ["commission", "collection", "sixth"],
    ["gauge-station", "chat-quote-fill", "sixth"],
    ["state", "collection", "sixth"],
    ["city", "grid", "sixth"],
    // ["equipment", "people-circle", "sixth"],
    // ["harbor", "grid", "sixth"],
    // ["institution", "collection", "sixth"],
    // ["manufacturer", "collection", "sixth"],
    // ["observer", "collection", "sixth"],
    // ["om", "collection", "sixth"],
    // ["platform", "calendar3", "sixth"],
    // ["platform_category", "chat-quote-fill", "sixth"],
    // ["researcher", "collection", "sixth"],
    // ["station", "chm", "sixth"],
    // ["stationCategory", "gear-fill", "sixth"],
    // ["stationOffShore", "speedometer", "sixth"],
    // ["stationOnShore", "toggles2", "sixth"],
    // ["surveying", "collection", "sixth"],
    // ["user", "grid", "sixth"],
    // ["tooltip role", "chevron-right", "sixth"]
]