import { Identifiable, initialHateoas } from "./identifiable";
import { initialLot, Lot } from "./lot";

export interface Item extends Identifiable {
    readonly id: string,
    sku: string,
    gtin: string,
    ncm: string,
    cest: string,
    cfop: string,
    category: string,
    brand: string,
    model: string,
    minimumStock: number,
    maximumStock: number,
    reservedStock: number,
    availableStock: number,
    bulk: number,
    grossWeightMeasurement: number,
    netWeightMeasurement: number,
    grossWeight: number,
    netWeight: number,
    url: string,
    lot: Lot,
}
export interface ItemValidation {
    readonly id: string,
    readonly sku: string,
    readonly gtin: string,
    readonly ncm: string,
    readonly cest: string,
    readonly cfop: string,
    readonly category: string,
    readonly brand: string,
    readonly model: string,
    readonly minimumStock: string,
    readonly maximumStock: string,
    readonly reservedStock: string,
    readonly availableStock: string,
    readonly bulk: string,
    readonly grossWeightMeasurement: string,
    readonly netWeightMeasurement: string,
    readonly grossWeight: string,
    readonly netWeight: string,
    readonly url: string,
    readonly lot: string,
}
export const initialItemValidation: ItemValidation = {
    id: `^[a-zA-Z0-9]+$`,
    sku: `^[a-zA-Z0-9]+$`,
    gtin: `^[a-zA-Z0-9]+$`,
    ncm: `^[a-zA-Z0-9]+$`,
    cest: `^[a-zA-Z0-9]+$`,
    cfop: `^[a-zA-Z0-9]+$`,
    category: `^[a-zA-Z0-9]+$`,
    brand: `^[a-zA-Z0-9]+$`,
    model: `^[a-zA-Z0-9]+$`,
    minimumStock: `^[0-9]+$`,
    maximumStock: `^[0-9]+$`,
    reservedStock: `^[0-9]+$`,
    availableStock: `^[0-9]+$`,
    bulk: `^[0-9]+$`,
    grossWeightMeasurement: `^[0-9]+$`,
    netWeightMeasurement: `^[0-9]+$`,
    grossWeight: `^[0-9]+$`,
    netWeight: `^[0-9]+$`,
    url: `^[a-zA-Z0-9]+$`,
    lot: `^[a-zA-Z0-9]+$`,
}
export const initialItem: Item = {
    id: '',
    links: initialHateoas,
    sku: '',
    gtin: '',
    ncm: '',
    cest: '',
    cfop: '',
    category: '',
    brand: '',
    model: '',
    minimumStock: 0,
    maximumStock: 0,
    reservedStock: 0,
    availableStock: 0,
    bulk: 0,
    grossWeightMeasurement: 0,
    netWeightMeasurement: 0,
    grossWeight: 0,
    netWeight: 0,
    url: '',
    lot: initialLot,
}